[package]
name = "dynamo_poc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.12.0"
rusoto = { version = "0.24.2" }
rusoto_core = "0.47.0"
rusoto_dynamodb = "0.47.0"